### ISSUE TITLE
duplicate classes in artifact atomix-all version 1.0.0-rc9

### ISSUE THREAD

**Issue by sclausen** [atomix/atomix#202]
there are duplicates of java classes.
e.g. atomix-all includes atomix and both artifacts have an Atomix.class

**Comment by kuujo** [comment]
I'm not sure what you mean. There's only one Atomix class. I haven't had any issue with atomix-all. Can you submit a PR?

**Comment by sclausen** [comment]
Unfortunately I don't know where you configured atomix-all, this repository is atomix-parent, so I don't know where to look for the maybe misconfigured pom.

Here is a screenshot of the maven dependencies in my eclipse:
![overlapping-classes](https://cloud.githubusercontent.com/assets/916076/17430070/8a26d35a-5af2-11e6-9024-01d2acf8a637.png)

So, when I build my project, I got this messages:

[WARNING] atomix-all-1.0.0-rc9.jar, atomix-collections-1.0.0-rc9.jar define 95 overlappping classes: 
[WARNING]   - io.atomix.collections.internal.MultiMapCommands$RemoveValue
[WARNING]   - io.atomix.collections.internal.SetCommands$Contains
[WARNING]   - io.atomix.collections.internal.MapCommands$Clear
[WARNING]   - io.atomix.collections.DistributedMultiMap$Order
[WARNING]   - io.atomix.collections.internal.MultiMapCommands$Clear
[WARNING]   - io.atomix.collections.internal.MultiMapCommands$EntryCommand
[WARNING]   - io.atomix.collections.internal.MapCommands$KeySet
[WARNING]   - io.atomix.collections.internal.SetCommands$TypeResolver
[WARNING]   - io.atomix.collections.internal.QueueCommands$Element
[WARNING]   - io.atomix.collections.internal.MultiMapCommands$Remove
[WARNING]   - 85 more...
[WARNING] atomix-all-1.0.0-rc9.jar, atomix-groups-1.0.0-rc9.jar define 69 overlappping classes: 
[WARNING]   - io.atomix.group.internal.GroupCommands$MemberCommand
[WARNING]   - io.atomix.group.internal.MembersState$1
[WARNING]   - io.atomix.group.internal.GroupCommands
[WARNING]   - io.atomix.group.internal.GroupCommands$PropertyCommand
[WARNING]   - io.atomix.group.messaging.internal.MessageProducerService
[WARNING]   - io.atomix.group.internal.GroupCommands$MemberOperation
[WARNING]   - io.atomix.group.internal.GroupCommands$GroupOperation
[WARNING]   - io.atomix.group.messaging.internal.MemberMessageProducer
[WARNING]   - io.atomix.group.internal.QueueState
[WARNING]   - io.atomix.group.messaging.internal.GroupMessage
[WARNING]   - 59 more...
[WARNING] atomix-all-1.0.0-rc9.jar, catalyst-local-1.1.1.jar define 10 overlappping classes: 
[WARNING]   - io.atomix.catalyst.transport.local.LocalConnection$ContextualFuture
[WARNING]   - io.atomix.catalyst.transport.local.LocalConnection$HandlerHolder
[WARNING]   - io.atomix.catalyst.transport.local.LocalServer$1
[WARNING]   - io.atomix.catalyst.transport.local.LocalClient
[WARNING]   - io.atomix.catalyst.transport.local.LocalServer
[WARNING]   - io.atomix.catalyst.transport.local.LocalConnection
[WARNING]   - io.atomix.catalyst.transport.local.LocalServerRegistry
[WARNING]   - io.atomix.catalyst.transport.local.LocalServer$ListenerHolder
[WARNING]   - io.atomix.catalyst.transport.local.LocalConnection$1
[WARNING]   - io.atomix.catalyst.transport.local.LocalTransport
[WARNING] catalyst-serializer-1.1.1.jar, atomix-all-1.0.0-rc9.jar define 68 overlappping classes: 
[WARNING]   - io.atomix.catalyst.serializer.lang.CharacterArraySerializer
[WARNING]   - io.atomix.catalyst.serializer.PrimitiveTypeResolver$1
[WARNING]   - io.atomix.catalyst.serializer.collection.HashSetSerializer
[WARNING]   - io.atomix.catalyst.serializer.lang.FloatArraySerializer
[WARNING]   - io.atomix.catalyst.serializer.util.BigDecimalSerializer
[WARNING]   - io.atomix.catalyst.serializer.lang.DoubleArraySerializer
[WARNING]   - io.atomix.catalyst.serializer.lang.DoubleSerializer
[WARNING]   - io.atomix.catalyst.serializer.JdkTypeResolver
[WARNING]   - io.atomix.catalyst.serializer.util.JavaSerializableSerializer
[WARNING]   - io.atomix.catalyst.serializer.Identifier$1
[WARNING]   - 58 more...
[WARNING] atomix-all-1.0.0-rc9.jar, catalyst-common-1.1.1.jar define 16 overlappping classes: 
[WARNING]   - io.atomix.catalyst.util.hash.Murmur2Hasher
[WARNING]   - io.atomix.catalyst.util.Durations
[WARNING]   - io.atomix.catalyst.util.reference.ReferenceCounted
[WARNING]   - io.atomix.catalyst.util.QualifiedProperties
[WARNING]   - io.atomix.catalyst.util.PropertiesReader
[WARNING]   - io.atomix.catalyst.util.Managed
[WARNING]   - io.atomix.catalyst.util.LRUCache
[WARNING]   - io.atomix.catalyst.util.Builder
[WARNING]   - io.atomix.catalyst.util.hash.StringHasher
[WARNING]   - io.atomix.catalyst.CatalystException
[WARNING]   - 6 more...
[WARNING] atomix-all-1.0.0-rc9.jar, catalyst-netty-1.1.1.jar define 19 overlappping classes: 
[WARNING]   - io.atomix.catalyst.transport.netty.NettyServer$ServerHandler
[WARNING]   - io.atomix.catalyst.transport.netty.NettyServer$1
[WARNING]   - io.atomix.catalyst.transport.netty.NettyClient$1
[WARNING]   - io.atomix.catalyst.transport.netty.NettyTransport
[WARNING]   - io.atomix.catalyst.transport.netty.NettyOptions
[WARNING]   - io.atomix.catalyst.transport.netty.NettyConnection
[WARNING]   - io.atomix.catalyst.transport.netty.NettyClient
[WARNING]   - io.atomix.catalyst.transport.netty.NettyConnection$HandlerHolder
[WARNING]   - io.atomix.catalyst.transport.netty.NettyConnection$1
[WARNING]   - io.atomix.catalyst.transport.netty.NettyHandler
[WARNING]   - 9 more...
[WARNING] atomix-all-1.0.0-rc9.jar, atomix-concurrent-1.0.0-rc9.jar define 9 overlappping classes: 
[WARNING]   - io.atomix.concurrent.util.DistributedLockFactory
[WARNING]   - io.atomix.concurrent.internal.LockCommands$LockCommand
[WARNING]   - io.atomix.concurrent.DistributedLock
[WARNING]   - io.atomix.concurrent.internal.LockCommands
[WARNING]   - io.atomix.concurrent.internal.LockCommands$Unlock
[WARNING]   - io.atomix.concurrent.internal.LockCommands$Lock
[WARNING]   - io.atomix.concurrent.internal.LockCommands$TypeResolver
[WARNING]   - io.atomix.concurrent.internal.LockState
[WARNING]   - io.atomix.concurrent.internal.LockCommands$LockEvent
[WARNING] atomix-all-1.0.0-rc9.jar, catalyst-concurrent-1.1.1.jar define 17 overlappping classes: 
[WARNING]   - io.atomix.catalyst.concurrent.ThreadContext
[WARNING]   - io.atomix.catalyst.concurrent.Listeners
[WARNING]   - io.atomix.catalyst.concurrent.SingleThreadContext$1
[WARNING]   - io.atomix.catalyst.concurrent.NonBlockingFuture
[WARNING]   - io.atomix.catalyst.concurrent.CatalystThreadFactory
[WARNING]   - io.atomix.catalyst.concurrent.ThreadPoolContext
[WARNING]   - io.atomix.catalyst.concurrent.ThreadPoolContext$1
[WARNING]   - io.atomix.catalyst.concurrent.CatalystThread
[WARNING]   - io.atomix.catalyst.concurrent.ComposableFuture
[WARNING]   - io.atomix.catalyst.concurrent.BlockingFuture
[WARNING]   - 7 more...
[WARNING] catalyst-transport-1.1.1.jar, atomix-all-1.0.0-rc9.jar define 8 overlappping classes: 
[WARNING]   - io.atomix.catalyst.transport.Transport
[WARNING]   - io.atomix.catalyst.transport.Connection
[WARNING]   - io.atomix.catalyst.transport.MessageHandler
[WARNING]   - io.atomix.catalyst.transport.Transport$Builder
[WARNING]   - io.atomix.catalyst.transport.Client
[WARNING]   - io.atomix.catalyst.transport.TransportException
[WARNING]   - io.atomix.catalyst.transport.Address
[WARNING]   - io.atomix.catalyst.transport.Server
[WARNING] atomix-all-1.0.0-rc9.jar, atomix-variables-1.0.0-rc9.jar define 26 overlappping classes: 
[WARNING]   - io.atomix.variables.internal.ValueCommands$CompareAndSet
[WARNING]   - io.atomix.variables.internal.LongCommands$GetAndDecrement
[WARNING]   - io.atomix.variables.internal.ValueState
[WARNING]   - io.atomix.variables.internal.LongCommands$DecrementAndGet
[WARNING]   - io.atomix.variables.internal.LongCommands$LongCommand
[WARNING]   - io.atomix.variables.internal.LongState
[WARNING]   - io.atomix.variables.internal.LongCommands$GetAndIncrement
[WARNING]   - io.atomix.variables.internal.ValueCommands
[WARNING]   - io.atomix.variables.internal.ValueCommands$ValueQuery
[WARNING]   - io.atomix.variables.internal.LongCommands
[WARNING]   - 16 more...
[WARNING] atomix-all-1.0.0-rc9.jar, atomix-resource-manager-1.0.0-rc9.jar define 40 overlappping classes: 
[WARNING]   - io.atomix.manager.AtomixException
[WARNING]   - io.atomix.manager.ResourceServer$1
[WARNING]   - io.atomix.manager.internal.KeyOperation
[WARNING]   - io.atomix.manager.options.ClientOptions
[WARNING]   - io.atomix.manager.ResourceManagerException
[WARNING]   - io.atomix.manager.internal.ResourceExists
[WARNING]   - io.atomix.manager.resource.internal.InstanceClient$StateChangeListener
[WARNING]   - io.atomix.manager.ResourceClient$Builder
[WARNING]   - io.atomix.manager.internal.ResourceManagerState
[WARNING]   - io.atomix.manager.internal.GetResourceKeys
[WARNING]   - 30 more...
[WARNING] atomix-all-1.0.0-rc9.jar, copycat-server-1.1.4.jar define 156 overlappping classes: 
[WARNING]   - io.atomix.copycat.server.storage.entry.KeepAliveEntry
[WARNING]   - io.atomix.copycat.server.state.ServerSessionManager
[WARNING]   - io.atomix.copycat.server.storage.util.StorageSerialization
[WARNING]   - io.atomix.copycat.server.storage.compaction.MajorCompactionManager
[WARNING]   - io.atomix.copycat.server.state.ServerCommit
[WARNING]   - io.atomix.copycat.server.storage.snapshot.SnapshotWriter
[WARNING]   - io.atomix.copycat.server.state.ClusterState
[WARNING]   - io.atomix.copycat.server.state.ServerStateMachineContext
[WARNING]   - io.atomix.copycat.server.storage.compaction.CompactionTask
[WARNING]   - io.atomix.copycat.server.storage.SegmentManager$1
[WARNING]   - 146 more...
[WARNING] atomix-all-1.0.0-rc9.jar, copycat-protocol-1.1.4.jar define 82 overlappping classes: 
[WARNING]   - io.atomix.copycat.error.ApplicationException
[WARNING]   - io.atomix.copycat.protocol.RegisterRequest$Builder
[WARNING]   - io.atomix.copycat.protocol.ConnectResponse$Builder
[WARNING]   - io.atomix.copycat.session.ClosedSessionException
[WARNING]   - io.atomix.copycat.protocol.AbstractResponse$Builder
[WARNING]   - io.atomix.copycat.protocol.CommandRequest
[WARNING]   - io.atomix.copycat.protocol.QueryResponse
[WARNING]   - io.atomix.copycat.protocol.OperationResponse
[WARNING]   - io.atomix.copycat.protocol.ConnectResponse
[WARNING]   - io.atomix.copycat.error.ConfigurationException
[WARNING]   - 72 more...
[WARNING] atomix-all-1.0.0-rc9.jar, copycat-client-1.1.4.jar define 42 overlappping classes: 
[WARNING]   - io.atomix.copycat.client.ConnectionStrategies$3
[WARNING]   - io.atomix.copycat.client.session.ClientSessionListener
[WARNING]   - io.atomix.copycat.client.ConnectionStrategies
[WARNING]   - io.atomix.copycat.client.session.ClientSessionState
[WARNING]   - io.atomix.copycat.client.RecoveryStrategies$1
[WARNING]   - io.atomix.copycat.client.RecoveryStrategy
[WARNING]   - io.atomix.copycat.client.ServerSelectionStrategies
[WARNING]   - io.atomix.copycat.client.CopycatClient
[WARNING]   - io.atomix.copycat.client.session.ClientSequencer$ResponseCallback
[WARNING]   - io.atomix.copycat.client.session.ClientSessionSubmitter$CommandAttempt
[WARNING]   - 32 more...
[WARNING] atomix-all-1.0.0-rc9.jar, atomix-1.0.0-rc9.jar define 20 overlappping classes: 
[WARNING]   - io.atomix.AtomixClient$1
[WARNING]   - io.atomix.AtomixReplica$CombinedClientTransport
[WARNING]   - io.atomix.Atomix
[WARNING]   - io.atomix.AtomixClient$Builder
[WARNING]   - io.atomix.AtomixReplica$CombinedClient
[WARNING]   - io.atomix.AtomixReplica$CombinedCopycatClient
[WARNING]   - io.atomix.cluster.BalancingClusterManager$Builder
[WARNING]   - io.atomix.cluster.Quorum
[WARNING]   - io.atomix.AtomixReplica$CombinedSelectionStrategy
[WARNING]   - io.atomix.AtomixReplica$CombinedServer
[WARNING]   - 10 more...
[WARNING] catalyst-buffer-1.1.1.jar, atomix-all-1.0.0-rc9.jar define 55 overlappping classes: 
[WARNING]   - io.atomix.catalyst.buffer.SwappedBuffer
[WARNING]   - io.atomix.catalyst.buffer.HeapBytes
[WARNING]   - io.atomix.catalyst.buffer.BufferDataOutput
[WARNING]   - io.atomix.catalyst.buffer.PooledDirectAllocator
[WARNING]   - io.atomix.catalyst.buffer.FileBuffer
[WARNING]   - io.atomix.catalyst.buffer.UnpooledAllocator
[WARNING]   - io.atomix.catalyst.buffer.DirectBufferPool$1
[WARNING]   - io.atomix.catalyst.buffer.MappedBuffer
[WARNING]   - io.atomix.catalyst.buffer.BufferAllocator
[WARNING]   - io.atomix.catalyst.buffer.HeapBufferPool$1
[WARNING]   - 45 more...
[WARNING] atomix-all-1.0.0-rc9.jar, atomix-resource-1.0.0-rc9.jar define 22 overlappping classes: 
[WARNING]   - io.atomix.resource.internal.ResourceCommand$Delete
[WARNING]   - io.atomix.resource.internal.ResourceQuery$Config
[WARNING]   - io.atomix.resource.ReadConsistency
[WARNING]   - io.atomix.resource.AbstractResource
[WARNING]   - io.atomix.resource.ResourceException
[WARNING]   - io.atomix.resource.internal.ResourceQuery
[WARNING]   - io.atomix.resource.ResourceTypeInfo
[WARNING]   - io.atomix.resource.ResourceStateMachine
[WARNING]   - io.atomix.resource.Resource
[WARNING]   - io.atomix.resource.ResourceRegistry
[WARNING]   - 12 more...

**Comment by sclausen** [comment]
As you can see in the screenshot, all classes from the artifacts `atomix-*`,  `copycat` and `catalyst` are bundled in `atomix-all` and the artifacts themself are also referenced as dependencies, so they are all overlapping.

**Comment by ccleve** [comment]
The workaround is to not use atomix-all. Just use io.atomix:atomix, and depend on io.atomix.catalyst:catalyst-netty separately.

**Comment by sclausen** [comment]
@ccleve Yes, sorry, I forgot to mention that.

**Comment by zheilbron** [comment]
I think this may be because of the way maven-bundle-plugin is configured. The plugin is configured to export all classes under the `io.atomix` package. The resulting jar (bundle) contains both the `core/pom.xml` and all classes under `io.atomix`. When maven is instructed to depend on this bundle, all of the `io.atomix` classes are added *and* the pom file's dependencies are resolved via maven, adding the classes again.

**Comment by sclausen** [comment]
So this issue is closed, because the error is resolved, or you don't care about this situation?

**Comment by kuujo** [comment]
All Atomix 1.x issues are being closed as it's no longer maintained. But I'll leave this open and will accept a PR. The `atomix-all` configuration is in `all/pom.xml`

**Comment by zheilbron** [comment]
Per my last comment, this issue is relevant to Atomix 2.x (atomix-2.0.3).

**Comment by johnou** [comment]
@zheilbron I don't think so? http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.atomix%22%20AND%20a%3A%22atomix-all%22 doesn't show any atomix-all artifact for 2.x and the all module does not exist in the 2.0 branch.

**Comment by zheilbron** [comment]
I just tried depending on `io.atomix:atomix:2.0.12` via maven and was still able to reproduce the issue. It's not called `atomix-all` anymore, but the root issue of seeing duplicate classes still exists.

**Comment by johnou** [comment]
@zheilbron can you show me your project pom.xml dependencies?

**Comment by zheilbron** [comment]
It's just this single dependency:
```
<dependency>
    <groupId>io.atomix</groupId>
    <artifactId>atomix</artifactId>
    <version>2.0.12</version>
</dependency>
```
